#!/bin/bash

if [ 2 -eq 4 ]; then
  echo Passed
elif [ 1 -eq 1 ]; then
  echo Second test passed
else
  echo "Bye"
fi

a=$(cat file1.txt)
b=$(cat file2.txt)
c=$(cat file3.txt)

if [ $a = $b ] && [ $a = $c ]; then
  rm file2.txt file3.txt
else
  echo "Files do not match"
fi
