#!/bin/bash

echo "My name is $1"
echo "My home directory is $2"
echo "My favorite color is $3"
echo "The 10th argument is ${10}"
echo "The 11th argument is ${11}"
echo $#
echo $@
#touch "$@"

# $* is same as $@

# There are some differences in between "$*" where we can separate words using our own IFS

IFS=,
echo "$*"
