#!/bin/bash

read -p "Enter your first name: " fname
read -p "Enter your surname/family name: " lname

PS3="Does your work include Headset or Handheld?: "
select phone in Headset Handheld;
do
  echo "You chose $phone"
  break
done

PS3="Please select your department: "
select department in Finance Sales "Customer Service" Engineering;
do
  echo "You chose $department"
  break
done

read -N 4 -p "What is your extension number?: " extention
echo ""
read -s -N 4 -p "What access code would you like to use when dialing in?: " accesscode
echo ""

echo "$fname,$lname,$extention,$accesscode,$phone,$department" >> extention.csv
