#!/bin/bash

while getopts "m:s:" opt; do
  case "$opt" in
    m) total_seconds=$(($total_seconds + (60*$OPTARG)));;
    s) total_seconds=$(($total_seconds + $OPTARG));;
    ?) ;;
  esac
done

while [ $total_seconds -gt 0 ]; do
  echo $total_seconds
  total_seconds=$(($total_seconds-1))
  sleep 1s
done

echo "TIME'S UP!!!"
