#!/bin/bash

PS3="Select a city of your choice: "

select city in Tokyo London "Los Angeles" Moscow Dubai Manchester "New York" Paris Bangalore Johannesburg Istanbul Milan "Abu Dhabi" Pune Nairobi Berlin Karachi;
do
  case "$city" in
    "Tokyo") echo "Japan";;
    "London" | "Manchester") echo "England";;
    "Los Angeles" | "New York") echo "United States of America";;
    "Moscow") echo "Russia";;
    "Dubai" | "Abu Dhabi") echo "United Arab Emirates";;
    "Paris") echo "France";;
    "Bangalore" | "Pune") echo "India";;
    "Johannesburg") echo "South Africa";;
    "Istanbul") echo "Turkey";;
    "Milan") echo "Italy";;
    "Nairobi") echo "Kenya";;
    "Berlin") echo "Germany";;
    "Karachi") echo "Pakistan";;
    *) echo "Wrong Choice";;
  esac
  break
done

exit 0
